# Generated by Django 3.2.3 on 2021-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('StudentMob', models.CharField(max_length=10)),
                ('StudentEmail', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
