# Generated by Django 3.2.3 on 2021-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teq', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Course',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='DOJ',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='Executive',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='Fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='LastFeesPaidOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='LeadLocation',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='LeadSource',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='ModeOfPayment',
            field=models.CharField(default='GooglePay', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='PaidFees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='PendingFees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='SelectedBatch',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
